@{
	# Office Documents
    'docx' = @('Productivity', 'Microsoft Word')
    'doc' = @('Productivity', 'Microsoft Word')
    'pptx' = @('Productivity', 'Microsoft PowerPoint')
	'ppt' = @('Office Documents', 'Microsoft PowerPoint')
	'csv' = @('Office Documents', 'Microsoft Excel')
	'pdf' = @('Office Documents', 'Adobe Acrobat')
	'xlsx' = @('Office Documents', 'Microsoft Excel')
	'ods' = @('Office Documents', 'OpenDocument Spreadsheet')
	'odt' = @('Office Documents', 'OpenDocument Text')
	'rtf' = @('Office Documents', 'Rich Text Format')
	'txt' = @('Office Documents', 'Text File')
	'key' = @('Office Documents', 'Keynote')
	'numbers' = @('Office Documents', 'Numbers')
	'pages' = @('Office Documents', 'Pages')
	'xlsm' = @('Office Documents', 'Excel Macro-Enabled')
	'xls' = @('Office Documents', 'Excel 97-2003')
	'odp' = @('Office Documents', 'OpenDocument Presentation')
	'slides' = @('Office Documents', 'Google Slides')
	'sheet' = @('Office Documents', 'Google Sheets')

	# Desktop Publishing (Limited to 20)
	'indd' = @('Desktop Publishing', 'Adobe InDesign')
	'qxd' = @('Desktop Publishing', 'QuarkXPress')
	'ai' = @('Desktop Publishing', 'Adobe Illustrator')
	'psd' = @('Desktop Publishing', 'Adobe Photoshop')
	'cdr' = @('Desktop Publishing', 'CorelDRAW')
	'svg' = @('Desktop Publishing', 'Scalable Vector Graphics')
	'eps' = @('Desktop Publishing', 'Encapsulated PostScript')
	'pub' = @('Desktop Publishing', 'Microsoft Publisher')
	'swf' = @('Desktop Publishing', 'Shockwave Flash')
	'xcf' = @('Desktop Publishing', 'GIMP')
	'fh' = @('Desktop Publishing', 'FreeHand')
	'pmd' = @('Desktop Publishing', 'Adobe PageMaker')
	'pdn' = @('Desktop Publishing', 'Paint.NET')
	'pixar' = @('Desktop Publishing', 'PIXAR')
	'psb' = @('Desktop Publishing', 'Photoshop Large Document')
	'wbmp' = @('Desktop Publishing', 'Wireless Bitmap')

	# Email and Communication (Limited to 20)
	'nsf' = @('Email and Communication', 'Lotus Notes')
	'ntf' = @('Email and Communication', 'Lotus Notes')
	'eml' = @('Email and Communication', 'Email Message')
	'mbox' = @('Email and Communication', 'Mailbox File')
	'msg' = @('Email and Communication', 'Outlook Email')
	'vcf' = @('Email and Communication', 'vCard')
	'ics' = @('Email and Communication', 'iCalendar')
	'mime' = @('Email and Communication', 'MIME')
	'pst' = @('Email and Communication', 'Outlook Data File')
	'dbx' = @('Email and Communication', 'Outlook Express')
	'mbn' = @('Email and Communication', 'Mobile Phonebook')
	'vmsg' = @('Email and Communication', 'Voicemail')
	'p7s' = @('Email and Communication', 'PKCS #7 Signature')
	'pkpass' = @('Email and Communication', 'Passbook')
	'asc' = @('Email and Communication', 'ASCII Armored GPG')
	'p7m' = @('Email and Communication', 'PKCS #7 MIME')
	'p7c' = @('Email and Communication', 'PKCS #7 Certificates')
	'p7b' = @('Email and Communication', 'PKCS #7 Certificates')
	'p10' = @('Email and Communication', 'PKCS #10 Certificate')

	# Multimedia (Limited to 20)
	'prproj' = @('Multimedia', 'Adobe Premiere')
	'premiere' = @('Multimedia', 'Adobe Premiere')
	'wmv' = @('Multimedia', 'Windows Media Video')
	'wma' = @('Multimedia', 'Windows Media Audio')
	'mp3' = @('Multimedia', 'MP3 Audio')
	'aac' = @('Multimedia', 'AAC Audio')
	'mp4' = @('Multimedia', 'MP4 Video')
	'flac' = @('Multimedia', 'FLAC Audio')
	'mov' = @('Multimedia', 'MOV Video')
	'avi' = @('Multimedia', 'AVI Video')
	'mkv' = @('Multimedia', 'MKV Video')
	'ogg' = @('Multimedia', 'OGG Audio')
	'wav' = @('Multimedia', 'WAV Audio')
	'midi' = @('Multimedia', 'MIDI Audio')
	'3gp' = @('Multimedia', '3GP Video')
	'flv' = @('Multimedia', 'FLV Video')
	'asf' = @('Multimedia', 'ASF Video')
	'm4a' = @('Multimedia', 'M4A Audio')
	'm4v' = @('Multimedia', 'M4V Video')
	'vob' = @('Multimedia', 'VOB Video')

	# Graphics and Images (Limited to 20)
	'bmp' = @('Graphics and Images', 'Bitmap')
	'raf' = @('Graphics and Images', 'RAF Image')
	'jpeg' = @('Graphics and Images', 'JPEG Image')
	'png' = @('Graphics and Images', 'PNG Image')
	'gif' = @('Graphics and Images', 'GIF Image')
	'raw' = @('Graphics and Images', 'RAW Image')
	'nef' = @('Graphics and Images', 'NEF Image')
	'tiff' = @('Graphics and Images', 'TIFF Image')
	'ps' = @('Graphics and Images', 'PostScript')
	'ico' = @('Graphics and Images', 'Icon')
	'webp' = @('Graphics and Images', 'WebP')
	'heic' = @('Graphics and Images', 'HEIC')
	'jxr' = @('Graphics and Images', 'JPEG XR')
	'pict' = @('Graphics and Images', 'PICT')
	'pic' = @('Graphics and Images', 'PIC')
	'pct' = @('Graphics and Images', 'PCT')
	'pbm' = @('Graphics and Images', 'PBM')
	'pgm' = @('Graphics and Images', 'PGM')
	'ppm' = @('Graphics and Images', 'PPM')
	'pnm' = @('Graphics and Images', 'PNM')

	# Emulators (Limited to 20)
	'adf' = @('Emulators', 'Amiga Disk File')
	'hdf' = @('Emulators', 'Amiga Hard Disk File')
	'd64' = @('Emulators', 'Commodore 64 Disk Image')
	'a52' = @('Emulators', 'Atari 5200 ROM')
	'nes' = @('Emulators', 'Nintendo Entertainment System ROM')
	'dsk' = @('Emulators', 'Apple II Disk Image')
	'atr' = @('Emulators', 'Atari 800 Disk Image')
	'tap' = @('Emulators', 'Commodore 64 Tape Image')
	'st' = @('Emulators', 'Atari ST Disk Image')
	'gcm' = @('Emulators', 'GameCube ROM')
	'smc' = @('Emulators', 'Super Nintendo ROM')
	'z64' = @('Emulators', 'Nintendo 64 ROM')
	'gba' = @('Emulators', 'Game Boy Advance ROM')
	'gbc' = @('Emulators', 'Game Boy Color ROM')
	'gb' = @('Emulators', 'Game Boy ROM')
	'sms' = @('Emulators', 'Sega Master System ROM')
	'gen' = @('Emulators', 'Sega Genesis ROM')
	'md' = @('Emulators', 'Sega Mega Drive ROM')
	'nds' = @('Emulators', 'Nintendo DS ROM')

	# Archivers (Limited to 20)
	'zip' = @('Archives and Compression', 'ZIP')
	'lha' = @('Archives and Compression', 'LHA')
	'lzh' = @('Archives and Compression', 'LZH')
	'sit' = @('Archives and Compression', 'StuffIt')
	'rar' = @('Archives and Compression', 'RAR')
	'tar' = @('Archives and Compression', 'TAR')
	'gz' = @('Archives and Compression', 'GZ')
	'7z' = @('Archives and Compression', '7z')
	'bz2' = @('Archives and Compression', 'BZ2')
	'xz' = @('Archives and Compression', 'XZ')
	'jar' = @('Archives and Compression', 'Java Archive')
	'cab' = @('Archives and Compression', 'Cabinet File')
	'iso' = @('Archives and Compression', 'ISO Disk Image')
	'ace' = @('Archives and Compression', 'ACE')
	'arj' = @('Archives and Compression', 'ARJ')
	'z' = @('Archives and Compression', 'Z')
	'rpm' = @('Archives and Compression', 'Red Hat Package Manager')
	'deb' = @('Archives and Compression', 'Debian Package')
	'tgz' = @('Archives and Compression', 'GZipped Tar File')
	'img' = @('Archives and Compression', 'Disk Image')

	# Programmers (Limited to 20)
	'py' = @('Programming and Development', 'Python')
	'bas' = @('Programming and Development', 'Visual Basic')
	'prg' = @('Programming and Development', 'FoxPro')
	'js' = @('Programming and Development', 'JavaScript')
	'cpp' = @('Programming and Development', 'C++')
	'c' = @('Programming and Development', 'C')
	'java' = @('Programming and Development', 'Java')
	'cs' = @('Programming and Development', 'C#')
	'rb' = @('Programming and Development', 'Ruby')
	'php' = @('Programming and Development', 'PHP')
	'html' = @('Programming and Development', 'HTML')
	'css' = @('Programming and Development', 'CSS')
	'json' = @('Programming and Development', 'JSON')
	'xml' = @('Programming and Development', 'XML')
	'sql' = @('Programming and Development', 'SQL')
	'go' = @('Programming and Development', 'Go')
	'rs' = @('Programming and Development', 'Rust')
	'ts' = @('Programming and Development', 'TypeScript')
	'sh' = @('Programming and Development', 'Shell Script')
	'pl' = @('Programming and Development', 'Perl')
}
